# -*- coding: utf-8 -*-
"""clean_and_eda.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1487rcfzjx1PnEToQJEfzrGIrcD8DrZdz

# Task 1 — Load and Inspect the Data
### The three raw CSV datasets are loaded into pandas DataFrames. Their dimensions and sample records are inspected before any cleaning is performed.
"""

from google.colab import files
from pathlib import Path

data_dir = Path("data")
data_dir.mkdir(exist_ok=True)

for filename in ["customers.csv", "products.csv", "orders.csv"]:
    print(f"Select only: {filename}")
    uploaded = files.upload()

    if len(uploaded) != 1:
        raise ValueError("Please select one file at a time.")

    file_content = next(iter(uploaded.values()))
    (data_dir / filename).write_bytes(file_content)

    print(f"Saved: data/{filename}")

import pandas as pd

# Load the raw CSV datasets.
orders = pd.read_csv("data/orders.csv")
customers = pd.read_csv("data/customers.csv")
products = pd.read_csv("data/products.csv")

# Display dataset dimensions before cleaning.
print("Orders:", orders.shape)
print("Customers:", customers.shape)
print("Products:", products.shape)

# Inspect the first five records from each dataset.
print("\nOrders preview:")
print(orders.head())

print("\nCustomers preview:")
print(customers.head())

print("\nProducts preview:")
print(products.head())

"""## Task 2 — Standardize Payment Method Labels
### Payment method labels are inspected for inconsistent capitalization. Leading and trailing spaces are removed, and all labels are converted to uppercase to ensure consistent grouping in subsequent analysis.
"""

# Inspect payment methods before standardization.
print("Payment methods before standardization:")
print(orders["payment_method"].unique())

print("\nNumber of distinct values before:")
print(orders["payment_method"].nunique())

# Remove surrounding spaces and standardize capitalization.
orders["payment_method"] = (
    orders["payment_method"].str.strip().str.upper()
)

# Verify the standardized labels and their counts.
print("\nPayment methods after standardization:")
print(orders["payment_method"].unique())

print("\nNumber of distinct values after:")
print(orders["payment_method"].nunique())

print("\nOrder count by payment method:")
print(orders["payment_method"].value_counts())

"""# Task 3 — Identify and Remove Duplicate Orders
### Duplicate orders are identified using all order attributes except order_id, since duplicate transactions have different order IDs. The first occurrence is retained, and subsequent duplicates are removed. The excluded records are preserved separately for revenue reconciliation.
"""

# Define the attributes used to identify duplicate transactions.
natural_key = [
    "customer_id",
    "product_id",
    "order_date",
    "quantity",
    "discount_pct",
    "payment_method",
    "rating",
    "returned",
]

# Flag duplicates while retaining the first occurrence.
duplicate_mask = orders.duplicated(
    subset=natural_key,
    keep="first"
)

# Preserve dropped rows for the revenue reconciliation in Task 5.
dropped_orders = orders.loc[duplicate_mask].copy()

print("Number of duplicate orders:", duplicate_mask.sum())

print("\nDropped order IDs:")
print(dropped_orders["order_id"].to_string(index=False))

# Create a separate dataset containing only retained orders.
orders_clean = orders.loc[~duplicate_mask].copy()

print("\nDataset dimensions after removing duplicates:")
print(orders_clean.shape)

"""# Task 4 — Handle Missing Discounts and Ratings
### Missing values are counted after duplicate removal. Missing discounts are replaced with 0%, following the business rule that no promotion was applied. Missing ratings are replaced with the median of the available ratings. The affected row counts and remaining missing values are printed to verify the changes.
"""

# Count missing values in the deduplicated dataset.
missing_discounts = orders_clean["discount_pct"].isnull().sum()
missing_ratings = orders_clean["rating"].isnull().sum()

print("Missing discounts before imputation:", missing_discounts)
print("Missing ratings before imputation:", missing_ratings)

# Calculate and display the median before filling missing ratings.
median_rating = orders_clean["rating"].median()
print("Median rating before imputation:", median_rating)

# Fill missing discounts and ratings.
orders_clean["discount_pct"] = (
    orders_clean["discount_pct"].fillna(0)
)

orders_clean["rating"] = (
    orders_clean["rating"].fillna(median_rating)
)

print("\nDiscount rows filled:", missing_discounts)
print("Rating rows filled:", missing_ratings)

# Verify that both columns contain no missing values.
print("\nMissing values after imputation:")
print(orders_clean[["discount_pct", "rating"]].isnull().sum())

"""# Task 5 — Merge Datasets and Reconcile Revenue
The cleaned orders are merged with product and customer details to calculate revenue after discounts. The raw revenue and the revenue associated with removed duplicates are calculated independently to explain the difference between the raw and cleaned totals.
"""

# Merge cleaned orders with product and customer details.
merged = (
    orders_clean
    .merge(products, on="product_id", how="left", validate="many_to_one")
    .merge(customers, on="customer_id", how="left", validate="many_to_one")
)

# Verify that every order has matching product and customer details.
assert merged["price"].notna().all(), "Some products did not match."
assert merged["name"].notna().all(), "Some customers did not match."

# Calculate revenue for each cleaned order.
merged["order_value"] = (
    merged["quantity"]
    * merged["price"]
    * (1 - merged["discount_pct"] / 100)
)

cleaned_total = merged["order_value"].sum()

print("Cleaned order count:", len(merged))
print(f"Cleaned total revenue: ₹{cleaned_total:,.2f}")

# Independently calculate revenue from all 180 original orders.
raw_revenue = orders.merge(
    products, on="product_id", how="left", validate="many_to_one"
)

raw_revenue["order_value"] = (
    raw_revenue["quantity"]
    * raw_revenue["price"]
    * (1 - raw_revenue["discount_pct"].fillna(0) / 100)
)

raw_total = raw_revenue["order_value"].sum()

# Independently calculate revenue from the five removed duplicates.
duplicate_revenue = dropped_orders.merge(
    products, on="product_id", how="left", validate="many_to_one"
)

duplicate_revenue["order_value"] = (
    duplicate_revenue["quantity"]
    * duplicate_revenue["price"]
    * (1 - duplicate_revenue["discount_pct"].fillna(0) / 100)
)

duplicate_total = duplicate_revenue["order_value"].sum()
revenue_difference = raw_total - cleaned_total

print("\nRevenue of removed duplicate orders:")
print(
    duplicate_revenue[["order_id", "order_value"]].to_string(
        index=False,
        float_format=lambda value: f"{value:.2f}"
    )
)

print(f"\nRaw total revenue: ₹{raw_total:,.2f}")
print(f"Removed duplicate revenue: ₹{duplicate_total:,.2f}")
print(f"Raw minus cleaned revenue: ₹{revenue_difference:,.2f}")

assert round(revenue_difference, 2) == round(duplicate_total, 2)

# Print the reconciliation explanation as part of the script output.
print(
    f"\nRevenue reconciliation: The raw CSV revenue of ₹{raw_total:,.2f} "
    f"corresponds to the total in Part 1 Report (a). After removing "
    f"{len(dropped_orders)} duplicate orders, revenue is "
    f"₹{cleaned_total:,.2f} across {len(merged)} retained orders. "
    f"The reduction of ₹{revenue_difference:,.2f} is entirely attributable "
    f"to the removed duplicates, whose independently calculated revenue "
    f"is ₹{duplicate_total:,.2f}. Discount imputation does not change "
    f"revenue because missing discounts are treated as 0% in both "
    f"calculations. Rating imputation has no effect on revenue because "
    f"rating is not used in the order-value formula."
)

"""# Task 6 — Identify Unusually Large Order Quantities
The interquartile range (IQR) is used to identify unusually large or small order quantities. Orders outside the calculated bounds are flagged and retained in the dataset so that their impact on monthly revenue can be evaluated later.
"""

# Calculate quartiles and the interquartile range.
Q1 = merged["quantity"].quantile(0.25)
Q3 = merged["quantity"].quantile(0.75)
IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

print("Q1:", Q1)
print("Q3:", Q3)
print("IQR:", IQR)
print("Lower bound:", lower)
print("Upper bound:", upper)

# Flag outliers without removing them from the merged dataset.
merged["is_outlier"] = (
    (merged["quantity"] < lower)
    | (merged["quantity"] > upper)
)

outliers = merged.loc[
    merged["is_outlier"],
    ["order_id", "order_date", "quantity"]
]

print("\nNumber of outlier orders:", len(outliers))
print("\nOutlier orders:")
print(outliers.to_string(index=False))

print("\nTotal orders retained:", len(merged))

"""# Task 7 — Compare Return Rates Across Payment Methods
The hypothesis is that cash-on-delivery (COD) orders have a higher return rate than Card and UPI orders. Order counts and average return indicators are calculated for each payment method. Since returned orders are coded as 1 and non-returned orders as 0, the mean represents the return rate.
"""

# State the hypothesis explicitly in the output.
print(
    "Hypothesis: COD orders have a higher return rate "
    "than Card and UPI orders."
)

# Calculate order counts and return rates.
payment_summary = (
    merged.groupby("payment_method")["returned"]
    .agg(["count", "mean"])
)

payment_summary["return_rate_pct"] = (
    payment_summary["mean"] * 100
)

print("\nReturn rates by payment method:")
print(
    payment_summary.to_string(
        formatters={
            "mean": "{:.4f}".format,
            "return_rate_pct": "{:.1f}%".format,
        }
    )
)

# Compare COD with both other payment methods.
cod_rate = payment_summary.loc["COD", "mean"]
card_rate = payment_summary.loc["CARD", "mean"]
upi_rate = payment_summary.loc["UPI", "mean"]

if cod_rate > card_rate and cod_rate > upi_rate:
    print(
        "\nHypothesis: Confirmed. "
        "COD has the highest observed return rate in this dataset."
    )
else:
    print(
        "\nHypothesis: Not confirmed. "
        "COD does not have a higher return rate than both alternatives."
    )

"""# Task 8 — Segment Return Risk by Payment Method and City Tier
Orders are grouped by payment method and city tier to examine differences in return rates across customer segments. The segment with the highest observed return rate is identified, and COD orders are compared across tiers to assess whether the overall COD rate conceals a concentration of risk.
"""

# Calculate order counts and return rates for each segment.
segment_summary = (
    merged.groupby(["payment_method", "city_tier"])["returned"]
    .agg(["count", "mean"])
)

segment_summary["return_rate_pct"] = (
    segment_summary["mean"] * 100
)

print("Return rates by payment method and city tier:")
print(
    segment_summary[["count", "return_rate_pct"]].to_string(
        formatters={"return_rate_pct": "{:.1f}%".format}
    )
)

# Identify the segment with the highest return rate.
highest_segment = segment_summary["return_rate_pct"].idxmax()
highest_rate = segment_summary.loc[
    highest_segment, "return_rate_pct"
]

payment_method, city_tier = highest_segment

print(
    f"\nHighest-risk segment: {payment_method} + "
    f"Tier-{city_tier} cities at {highest_rate:.1f}%."
)

# Compare COD orders across the two city tiers.
cod_segments = segment_summary.loc["COD"]

tier1_count = int(cod_segments.loc[1, "count"])
tier2_count = int(cod_segments.loc[2, "count"])
tier1_rate = cod_segments.loc[1, "return_rate_pct"]
tier2_rate = cod_segments.loc[2, "return_rate_pct"]

print(
    f"\nCOD comparison: Tier-1 cities have {tier1_count} orders "
    f"with a {tier1_rate:.1f}% return rate, while Tier-2 cities "
    f"have {tier2_count} orders with a {tier2_rate:.1f}% return rate. "
    "The difference shows that COD return risk is not uniform "
    "across city tiers; the overall COD rate masks this variation."
)

"""# Task 9 — Assess Relationships Between Numeric Variables
Pearson correlations are calculated for rating, return status, discount percentage, and quantity. Each unique pair is classified by its absolute correlation strength: negligible below 0.2, weak from 0.2 to below 0.4, moderate from 0.4 to below 0.7, and strong from 0.7 to 1.0. The relationship between discounts and returns is examined to evaluate whether higher discounts are associated with fewer returns.
"""

from itertools import combinations

# Calculate correlations using all retained orders, including outliers.
correlation_columns = [
    "rating",
    "returned",
    "discount_pct",
    "quantity",
]

correlation_matrix = merged[correlation_columns].corr()

print("Pearson correlation matrix:")
print(correlation_matrix.round(3).to_string())

# Classify strength using the absolute, unrounded correlation.
def correlation_strength(value):
    magnitude = abs(value)

    if magnitude < 0.2:
        return "negligible"
    elif magnitude < 0.4:
        return "weak"
    elif magnitude < 0.7:
        return "moderate"
    else:
        return "strong"

# Print all six unique pairwise correlations and their classifications.
print("\nPairwise correlation strengths:")

for first, second in combinations(correlation_columns, 2):
    value = correlation_matrix.loc[first, second]
    strength = correlation_strength(value)

    print(f"{first} vs {second}: r = {value:.3f} — {strength}")

# Evaluate the discount-return hypothesis.
discount_return_corr = correlation_matrix.loc[
    "discount_pct", "returned"
]

print("\nHypothesis: Higher discounts reduce returns.")

if abs(discount_return_corr) < 0.2:
    print(
        f"Hypothesis: Busted. The correlation between discount percentage "
        f"and returns is {discount_return_corr:.3f}, indicating a negligible "
        "linear relationship. This analysis does not support the claim "
        "that higher discounts reduce returns."
    )
else:
    print(
        f"The observed correlation is {discount_return_corr:.3f}; "
        "review its direction and strength before drawing a conclusion."
    )

print("Correlation alone does not establish causation.")

"""# Task 10 — Evaluate the Impact of Bulk Orders on Monthly Revenue
Order dates are converted to datetime and grouped by year and month. Monthly revenue is calculated both including and excluding the quantity outliers identified in Task 6. The two series are compared to determine whether unusually large orders influence the apparent peak month.
"""

# Convert order dates and extract year-month.
merged["order_date"] = pd.to_datetime(merged["order_date"])
merged["year_month"] = merged["order_date"].dt.to_period("M")

# Calculate monthly revenue including all retained orders.
monthly_revenue_all = (
    merged.groupby("year_month")["order_value"]
    .sum()
    .sort_index()
)

# Calculate monthly revenue excluding flagged quantity outliers.
monthly_revenue_corrected = (
    merged.loc[~merged["is_outlier"]]
    .groupby("year_month")["order_value"]
    .sum()
    .sort_index()
)

print("Monthly revenue including quantity outliers (₹):")
print(monthly_revenue_all.to_string(float_format="{:.2f}".format))

print("\nMonthly revenue excluding quantity outliers (₹):")
print(
    monthly_revenue_corrected.to_string(
        float_format="{:.2f}".format
    )
)

# Display the bulk orders responsible for the difference.
print("\nFlagged bulk orders:")
print(
    merged.loc[
        merged["is_outlier"],
        ["order_id", "order_date", "quantity", "order_value"]
    ].to_string(index=False, float_format="{:.2f}".format)
)

# Identify the peak month in each series.
peak_all = monthly_revenue_all.idxmax()
peak_corrected = monthly_revenue_corrected.idxmax()

print(
    f"\nPeak including outliers: {peak_all} "
    f"(₹{monthly_revenue_all.loc[peak_all]:,.2f})"
)

print(
    f"Peak excluding outliers: {peak_corrected} "
    f"(₹{monthly_revenue_corrected.loc[peak_corrected]:,.2f})"
)

# Explain the effect of the January bulk orders.
print(
    "\nFinding: January's apparent revenue lead is an artifact of "
    "two bulk orders: O0011 on 2026-01-28 (25 units) and O0098 "
    "on 2026-01-10 (30 units). Once these orders are excluded, "
    "March is the genuine peak month in the outlier-corrected series. "
    "The flagged orders remain in the merged dataset; they are excluded "
    "only from the corrected monthly calculation."
)